--CRIAÇÃO DO BANCO

CREATE DATABASE loja;
USE LOJA;
SHOW DATABASES;

CREATE TABLE cliente(
	CLIENTE_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_NOME VARCHAR(50) NOT NULL,
	CLIENTE_END VARCHAR(50) NOT NULL,
	CLIENTE_END_CIDADE VARCHAR(20) NOT NULL,
	ESTADO_CODIGO CHAR(2) NOT NULL,
	CLIENTE_END_CEP CHAR(8) NOT NULL,
	CLIENTE_TELEFONE CHAR(10) NOT NULL,
	CLIENTE_PERC_DESCONTO DECIMAL(2,0)
);


CREATE TABLE produto(
	PRODUTO_ID SMALLINT(6) PRIMARY KEY AUTO_INCREMENT,
	PRODUTO_NOME VARCHAR(40) NOT NULL,
	PRODUTO_PRECO DECIMAL(5,2) NOT NULL,
	UE_PRODUTO_COD CHAR(3)

);

CREATE TABLE item(
	PEDIDO_ID INT(11) PRIMARY KEY AUTO_INCREMENT,
	PRODUTO_ID SMALLINT(6) NOT NULL,
	ITEM_QUANTIDADE SMALLINT(6) NOT NULL,
	ITEM_VALOR_UNITARIO DECIMAL(5,2),
	ITEM_VALOR_TOTAL DECIMAL(5,2)
);

CREATE TABLE pedido(
	PEDIDO_ID INT(11),
	PRODUTO_ID SMALLINT(6)
);
