/* Modelagem Básica */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDEREÇO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 É FEITA PELO ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA/AD */
MODELAGEM FÍSICA - SCRIPTS DE BANCO

/*Não se escreve diretamente um comando no mysql, usam-se editores de texto*/

/* INICIANDO A MODELAGEM FÍSICA  */
CREATE DATABASE PROJETO;

CREATE DATABASE EXEMPLO;

/* CONECTANDO-SE AO BANCO */
USE PROJETO;

/* CONECTANDO A TABELA DE CLIENTES */
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	CPF INT(11),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(30),
	ENDEREÇO VARCHAR(100),
	SEXO VARCHAR(1)
);


/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;
